services:
  app:
    build: .
    ports:
      - 9000:9000
    networks:
      - dnetwork
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - app-data:/app/data
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cineflix
    ports:
      - 5433:5432
    networks:
      - dnetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  dnetwork:
    driver: bridge

volumes:
  postgres-data:
  app-data: