services:
  app:
    build: .
    ports:
      - 9000:9000
    networks:
      - dnetwork
    environment:
      SPRING_PROFILES_ACTIVE: prod
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - app-data:/app/data
    depends_on:
      - postgres
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - dnetwork

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - dnetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cineflix
    ports:
      - 5433:5432
    networks:
      - dnetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  dnetwork:
    driver: bridge

volumes:
  postgres-data:
  app-data: